-- Bangladesh Divisions, Districts, Upazilas Data Update (UTF-8)
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

UPDATE `divisions` SET `name` = 'বরিশাল' WHERE `id` = 1;
UPDATE `divisions` SET `name` = 'চট্টগ্রাম' WHERE `id` = 2;
UPDATE `divisions` SET `name` = 'ঢাকা' WHERE `id` = 3;
UPDATE `divisions` SET `name` = 'খুলনা' WHERE `id` = 4;
UPDATE `divisions` SET `name` = 'ময়মনসিংহ' WHERE `id` = 5;
UPDATE `divisions` SET `name` = 'রাজশাহী' WHERE `id` = 6;
UPDATE `divisions` SET `name` = 'রংপুর' WHERE `id` = 7;
UPDATE `divisions` SET `name` = 'সিলেট' WHERE `id` = 8;

UPDATE `districts` SET `name` = 'বরগুনা' WHERE `id` = 65;
UPDATE `districts` SET `name` = 'বরিশাল' WHERE `id` = 66;
UPDATE `districts` SET `name` = 'ভোলা' WHERE `id` = 67;
UPDATE `districts` SET `name` = 'ঝালকাঠি' WHERE `id` = 68;
UPDATE `districts` SET `name` = 'পটুয়াখালী' WHERE `id` = 69;
UPDATE `districts` SET `name` = 'পিরোজপুর' WHERE `id` = 70;
UPDATE `districts` SET `name` = 'বান্দরবান' WHERE `id` = 71;
UPDATE `districts` SET `name` = 'ব্রাহ্মণবাড়িয়া' WHERE `id` = 72;
UPDATE `districts` SET `name` = 'চাঁদপুর' WHERE `id` = 73;
UPDATE `districts` SET `name` = 'চট্টগ্রাম' WHERE `id` = 74;
UPDATE `districts` SET `name` = 'কুমিল্লা' WHERE `id` = 75;
UPDATE `districts` SET `name` = 'কক্সবাজার' WHERE `id` = 76;
UPDATE `districts` SET `name` = 'ফেনী' WHERE `id` = 77;
UPDATE `districts` SET `name` = 'খাগড়াছড়ি' WHERE `id` = 78;
UPDATE `districts` SET `name` = 'লক্ষ্মীপুর' WHERE `id` = 79;
UPDATE `districts` SET `name` = 'নোয়াখালী' WHERE `id` = 80;
UPDATE `districts` SET `name` = 'রাঙ্গামাটি' WHERE `id` = 81;
UPDATE `districts` SET `name` = 'ঢাকা' WHERE `id` = 82;
UPDATE `districts` SET `name` = 'ফরিদপুর' WHERE `id` = 83;
UPDATE `districts` SET `name` = 'গাজীপুর' WHERE `id` = 84;
UPDATE `districts` SET `name` = 'গোপালগঞ্জ' WHERE `id` = 85;
UPDATE `districts` SET `name` = 'কিশোরগঞ্জ' WHERE `id` = 86;
UPDATE `districts` SET `name` = 'মাদারীপুর' WHERE `id` = 87;
UPDATE `districts` SET `name` = 'মানিকগঞ্জ' WHERE `id` = 88;
UPDATE `districts` SET `name` = 'মুন্সিগঞ্জ' WHERE `id` = 89;
UPDATE `districts` SET `name` = 'নারায়ণগঞ্জ' WHERE `id` = 90;
UPDATE `districts` SET `name` = 'নরসিংদী' WHERE `id` = 91;
UPDATE `districts` SET `name` = 'রাজবাড়ী' WHERE `id` = 92;
UPDATE `districts` SET `name` = 'শরীয়তপুর' WHERE `id` = 93;
UPDATE `districts` SET `name` = 'টাঙ্গাইল' WHERE `id` = 94;
UPDATE `districts` SET `name` = 'বাগেরহাট' WHERE `id` = 95;
UPDATE `districts` SET `name` = 'চুয়াডাঙ্গা' WHERE `id` = 96;
UPDATE `districts` SET `name` = 'যশোর' WHERE `id` = 97;
UPDATE `districts` SET `name` = 'ঝিনাইদহ' WHERE `id` = 98;
UPDATE `districts` SET `name` = 'খুলনা' WHERE `id` = 99;
UPDATE `districts` SET `name` = 'কুষ্টিয়া' WHERE `id` = 100;
UPDATE `districts` SET `name` = 'মাগুরা' WHERE `id` = 101;
UPDATE `districts` SET `name` = 'মেহেরপুর' WHERE `id` = 102;
UPDATE `districts` SET `name` = 'নড়াইল' WHERE `id` = 103;
UPDATE `districts` SET `name` = 'সাতক্ষীরা' WHERE `id` = 104;
UPDATE `districts` SET `name` = 'জামালপুর' WHERE `id` = 105;
UPDATE `districts` SET `name` = 'ময়মনসিংহ' WHERE `id` = 106;
UPDATE `districts` SET `name` = 'নেত্রকোণা' WHERE `id` = 107;
UPDATE `districts` SET `name` = 'শেরপুর' WHERE `id` = 108;
UPDATE `districts` SET `name` = 'বগুড়া' WHERE `id` = 109;
UPDATE `districts` SET `name` = 'জয়পুরহাট' WHERE `id` = 110;
UPDATE `districts` SET `name` = 'নওগাঁ' WHERE `id` = 111;
UPDATE `districts` SET `name` = 'নাটোর' WHERE `id` = 112;
UPDATE `districts` SET `name` = 'চাঁপাইনবাবগঞ্জ' WHERE `id` = 113;
UPDATE `districts` SET `name` = 'পাবনা' WHERE `id` = 114;
UPDATE `districts` SET `name` = 'রাজশাহী' WHERE `id` = 115;
UPDATE `districts` SET `name` = 'সিরাজগঞ্জ' WHERE `id` = 116;
UPDATE `districts` SET `name` = 'দিনাজপুর' WHERE `id` = 117;
UPDATE `districts` SET `name` = 'গাইবান্ধা' WHERE `id` = 118;
UPDATE `districts` SET `name` = 'কুড়িগ্রাম' WHERE `id` = 119;
UPDATE `districts` SET `name` = 'লালমনিরহাট' WHERE `id` = 120;
UPDATE `districts` SET `name` = 'নীলফামারী' WHERE `id` = 121;
UPDATE `districts` SET `name` = 'পঞ্চগড়' WHERE `id` = 122;
UPDATE `districts` SET `name` = 'রংপুর' WHERE `id` = 123;
UPDATE `districts` SET `name` = 'ঠাকুরগাঁও' WHERE `id` = 124;
UPDATE `districts` SET `name` = 'হবিগঞ্জ' WHERE `id` = 125;
UPDATE `districts` SET `name` = 'মৌলভীবাজার' WHERE `id` = 126;
UPDATE `districts` SET `name` = 'সুনামগঞ্জ' WHERE `id` = 127;
UPDATE `districts` SET `name` = 'সিলেট' WHERE `id` = 128;

UPDATE `upazilas` SET `name` = 'কচুয়া' WHERE `id` = 505;
UPDATE `upazilas` SET `name` = 'চিতলমারী' WHERE `id` = 506;
UPDATE `upazilas` SET `name` = 'ফকিরহাট' WHERE `id` = 507;
UPDATE `upazilas` SET `name` = 'বাগেরহাট সদর' WHERE `id` = 508;
UPDATE `upazilas` SET `name` = 'মোড়েলগঞ্জ' WHERE `id` = 509;
UPDATE `upazilas` SET `name` = 'মোংলা' WHERE `id` = 510;
UPDATE `upazilas` SET `name` = 'মোল্লাহাট' WHERE `id` = 511;
UPDATE `upazilas` SET `name` = 'রামপাল' WHERE `id` = 512;
UPDATE `upazilas` SET `name` = 'শরণখোলা' WHERE `id` = 513;
UPDATE `upazilas` SET `name` = 'আলীকদম' WHERE `id` = 514;
UPDATE `upazilas` SET `name` = 'থানচি' WHERE `id` = 515;
UPDATE `upazilas` SET `name` = 'নাইক্ষ্যংছড়ি' WHERE `id` = 516;
UPDATE `upazilas` SET `name` = 'বান্দরবান সদর' WHERE `id` = 517;
UPDATE `upazilas` SET `name` = 'রুমা' WHERE `id` = 518;
UPDATE `upazilas` SET `name` = 'রোয়াংছড়ি' WHERE `id` = 519;
UPDATE `upazilas` SET `name` = 'লামা' WHERE `id` = 520;
UPDATE `upazilas` SET `name` = 'আমতলী' WHERE `id` = 521;
UPDATE `upazilas` SET `name` = 'তালতলি' WHERE `id` = 522;
UPDATE `upazilas` SET `name` = 'পাথরঘাটা' WHERE `id` = 523;
UPDATE `upazilas` SET `name` = 'বরগুনা সদর' WHERE `id` = 524;
UPDATE `upazilas` SET `name` = 'বামনা' WHERE `id` = 525;
UPDATE `upazilas` SET `name` = 'বেতাগী' WHERE `id` = 526;
UPDATE `upazilas` SET `name` = 'আগৈলঝাড়া' WHERE `id` = 527;
UPDATE `upazilas` SET `name` = 'উজিরপুর' WHERE `id` = 528;
UPDATE `upazilas` SET `name` = 'গৌরনদী' WHERE `id` = 529;
UPDATE `upazilas` SET `name` = 'বরিশাল সদর' WHERE `id` = 530;
UPDATE `upazilas` SET `name` = 'বরিশাল সিটি কর্পোরেশন' WHERE `id` = 531;
UPDATE `upazilas` SET `name` = 'বাকেরগঞ্জ' WHERE `id` = 532;
UPDATE `upazilas` SET `name` = 'বানারীপাড়া' WHERE `id` = 533;
UPDATE `upazilas` SET `name` = 'বাবুগঞ্জ' WHERE `id` = 534;
UPDATE `upazilas` SET `name` = 'মুলাদী' WHERE `id` = 535;
UPDATE `upazilas` SET `name` = 'মেহেন্দিগঞ্জ' WHERE `id` = 536;
UPDATE `upazilas` SET `name` = 'হিজলা' WHERE `id` = 537;
UPDATE `upazilas` SET `name` = 'চরফ্যাশন' WHERE `id` = 538;
UPDATE `upazilas` SET `name` = 'তজুমদ্দিন' WHERE `id` = 539;
UPDATE `upazilas` SET `name` = 'দৌলতখান' WHERE `id` = 540;
UPDATE `upazilas` SET `name` = 'বোরহান উদ্দিন' WHERE `id` = 541;
UPDATE `upazilas` SET `name` = 'ভোলা সদর' WHERE `id` = 542;
UPDATE `upazilas` SET `name` = 'মনপুরা' WHERE `id` = 543;
UPDATE `upazilas` SET `name` = 'লালমোহন' WHERE `id` = 544;
UPDATE `upazilas` SET `name` = 'আদমদিঘি' WHERE `id` = 545;
UPDATE `upazilas` SET `name` = 'কাহালু' WHERE `id` = 546;
UPDATE `upazilas` SET `name` = 'গাবতলী' WHERE `id` = 547;
UPDATE `upazilas` SET `name` = 'দুপচাচিঁয়া' WHERE `id` = 548;
UPDATE `upazilas` SET `name` = 'ধুনট' WHERE `id` = 549;
UPDATE `upazilas` SET `name` = 'নন্দিগ্রাম' WHERE `id` = 550;
UPDATE `upazilas` SET `name` = 'বগুড়া সদর' WHERE `id` = 551;
UPDATE `upazilas` SET `name` = 'শাজাহানপুর' WHERE `id` = 552;
UPDATE `upazilas` SET `name` = 'শিবগঞ্জ' WHERE `id` = 553;
UPDATE `upazilas` SET `name` = 'শেরপুর' WHERE `id` = 554;
UPDATE `upazilas` SET `name` = 'সারিয়াকান্দি' WHERE `id` = 555;
UPDATE `upazilas` SET `name` = 'সোনাতলা' WHERE `id` = 556;
UPDATE `upazilas` SET `name` = 'আখাউড়া' WHERE `id` = 557;
UPDATE `upazilas` SET `name` = 'আশুগঞ্জ' WHERE `id` = 558;
UPDATE `upazilas` SET `name` = 'কসবা' WHERE `id` = 559;
UPDATE `upazilas` SET `name` = 'নবীনগর' WHERE `id` = 560;
UPDATE `upazilas` SET `name` = 'নাসিরনগর' WHERE `id` = 561;
UPDATE `upazilas` SET `name` = 'বাঞ্ছারামপুর' WHERE `id` = 562;
UPDATE `upazilas` SET `name` = 'বিজয়নগর' WHERE `id` = 563;
UPDATE `upazilas` SET `name` = 'ব্রাহ্মণবাড়িয়া সদর' WHERE `id` = 564;
UPDATE `upazilas` SET `name` = 'সরাইল' WHERE `id` = 565;
UPDATE `upazilas` SET `name` = 'কচুয়া' WHERE `id` = 566;
UPDATE `upazilas` SET `name` = 'চাঁদপুর সদর' WHERE `id` = 567;
UPDATE `upazilas` SET `name` = 'ফরিদগঞ্জ' WHERE `id` = 568;
UPDATE `upazilas` SET `name` = 'মতলব উত্তর' WHERE `id` = 569;
UPDATE `upazilas` SET `name` = 'মতলব দক্ষিণ' WHERE `id` = 570;
UPDATE `upazilas` SET `name` = 'শাহরাস্তি ' WHERE `id` = 571;
UPDATE `upazilas` SET `name` = 'হাইমচর' WHERE `id` = 572;
UPDATE `upazilas` SET `name` = 'হাজীগঞ্জ' WHERE `id` = 573;
UPDATE `upazilas` SET `name` = 'আনোয়ারা' WHERE `id` = 574;
UPDATE `upazilas` SET `name` = 'কর্ণফুলী' WHERE `id` = 575;
UPDATE `upazilas` SET `name` = 'চট্রগ্রাম সিটি কর্পোরেশন' WHERE `id` = 576;
UPDATE `upazilas` SET `name` = 'চন্দনাইশ' WHERE `id` = 577;
UPDATE `upazilas` SET `name` = 'পটিয়া' WHERE `id` = 578;
UPDATE `upazilas` SET `name` = 'ফটিকছড়ি' WHERE `id` = 579;
UPDATE `upazilas` SET `name` = 'বাঁশখালী' WHERE `id` = 580;
UPDATE `upazilas` SET `name` = 'বোয়ালখালী' WHERE `id` = 581;
UPDATE `upazilas` SET `name` = 'মীরসরাই' WHERE `id` = 582;
UPDATE `upazilas` SET `name` = 'রাউজান' WHERE `id` = 583;
UPDATE `upazilas` SET `name` = 'রাঙ্গুনিয়া' WHERE `id` = 584;
UPDATE `upazilas` SET `name` = 'লোহাগাড়া' WHERE `id` = 585;
UPDATE `upazilas` SET `name` = 'সন্দ্বীপ' WHERE `id` = 586;
UPDATE `upazilas` SET `name` = 'সাতকানিয়া' WHERE `id` = 587;
UPDATE `upazilas` SET `name` = 'সীতাকুন্ড' WHERE `id` = 588;
UPDATE `upazilas` SET `name` = 'হাটহাজারী' WHERE `id` = 589;
UPDATE `upazilas` SET `name` = 'আলমডাঙ্গা' WHERE `id` = 590;
UPDATE `upazilas` SET `name` = 'চুয়াডাঙ্গা সদর' WHERE `id` = 591;
UPDATE `upazilas` SET `name` = 'জীবননগর' WHERE `id` = 592;
UPDATE `upazilas` SET `name` = 'দামুড়হুদা' WHERE `id` = 593;
UPDATE `upazilas` SET `name` = 'কুমিল্লা সদর' WHERE `id` = 594;
UPDATE `upazilas` SET `name` = 'কুমিল্লা সিটি কর্পোরেশন' WHERE `id` = 595;
UPDATE `upazilas` SET `name` = 'চান্দিনা' WHERE `id` = 596;
UPDATE `upazilas` SET `name` = 'চৌদ্দগ্রাম' WHERE `id` = 597;
UPDATE `upazilas` SET `name` = 'তিতাস' WHERE `id` = 598;
UPDATE `upazilas` SET `name` = 'দাউদকান্দি' WHERE `id` = 599;
UPDATE `upazilas` SET `name` = 'দেবিদ্বার' WHERE `id` = 600;
UPDATE `upazilas` SET `name` = 'নাঙ্গলকোট' WHERE `id` = 601;
UPDATE `upazilas` SET `name` = 'বরুড়া' WHERE `id` = 602;
UPDATE `upazilas` SET `name` = 'বুড়িচং' WHERE `id` = 603;
UPDATE `upazilas` SET `name` = 'ব্রাহ্মণপাড়া' WHERE `id` = 604;
UPDATE `upazilas` SET `name` = 'মনোহরগঞ্জ' WHERE `id` = 605;
UPDATE `upazilas` SET `name` = 'মুরাদনগর' WHERE `id` = 606;
UPDATE `upazilas` SET `name` = 'মেঘনা' WHERE `id` = 607;
UPDATE `upazilas` SET `name` = 'লাকসাম' WHERE `id` = 608;
UPDATE `upazilas` SET `name` = 'লালমাই' WHERE `id` = 609;
UPDATE `upazilas` SET `name` = 'সদর দক্ষিণ' WHERE `id` = 610;
UPDATE `upazilas` SET `name` = 'হোমনা' WHERE `id` = 611;
UPDATE `upazilas` SET `name` = 'উখিয়া' WHERE `id` = 612;
UPDATE `upazilas` SET `name` = 'কক্সবাজার সদর' WHERE `id` = 613;
UPDATE `upazilas` SET `name` = 'কুতুবদিয়া' WHERE `id` = 614;
UPDATE `upazilas` SET `name` = 'চকরিয়া' WHERE `id` = 615;
UPDATE `upazilas` SET `name` = 'টেকনাফ' WHERE `id` = 616;
UPDATE `upazilas` SET `name` = 'পেকুয়া' WHERE `id` = 617;
UPDATE `upazilas` SET `name` = 'মহেশখালী' WHERE `id` = 618;
UPDATE `upazilas` SET `name` = 'রামু' WHERE `id` = 619;
UPDATE `upazilas` SET `name` = 'কেরাণীগঞ্জ' WHERE `id` = 620;
UPDATE `upazilas` SET `name` = 'ঢাকা উত্তর সিটি কর্পোরেশন' WHERE `id` = 621;
UPDATE `upazilas` SET `name` = 'ঢাকা দক্ষিণ সিটি কর্পোরেশন' WHERE `id` = 622;
UPDATE `upazilas` SET `name` = 'দোহার' WHERE `id` = 623;
UPDATE `upazilas` SET `name` = 'ধামরাই' WHERE `id` = 624;
UPDATE `upazilas` SET `name` = 'নবাবগঞ্জ' WHERE `id` = 625;
UPDATE `upazilas` SET `name` = 'সাভার' WHERE `id` = 626;
UPDATE `upazilas` SET `name` = 'কাহারোল' WHERE `id` = 627;
UPDATE `upazilas` SET `name` = 'খানসামা' WHERE `id` = 628;
UPDATE `upazilas` SET `name` = 'ঘোড়াঘাট' WHERE `id` = 629;
UPDATE `upazilas` SET `name` = 'চিরিরবন্দর' WHERE `id` = 630;
UPDATE `upazilas` SET `name` = 'দিনাজপুর সদর' WHERE `id` = 631;
UPDATE `upazilas` SET `name` = 'নবাবগঞ্জ' WHERE `id` = 632;
UPDATE `upazilas` SET `name` = 'পার্বতীপুর' WHERE `id` = 633;
UPDATE `upazilas` SET `name` = 'ফুলবাড়ী' WHERE `id` = 634;
UPDATE `upazilas` SET `name` = 'বিরল' WHERE `id` = 635;
UPDATE `upazilas` SET `name` = 'বিরামপুর' WHERE `id` = 636;
UPDATE `upazilas` SET `name` = 'বীরগঞ্জ' WHERE `id` = 637;
UPDATE `upazilas` SET `name` = 'বোচাগঞ্জ' WHERE `id` = 638;
UPDATE `upazilas` SET `name` = 'হাকিমপুর' WHERE `id` = 639;
UPDATE `upazilas` SET `name` = 'আলফাডাঙ্গা' WHERE `id` = 640;
UPDATE `upazilas` SET `name` = 'চরভদ্রাসন' WHERE `id` = 641;
UPDATE `upazilas` SET `name` = 'নগরকান্দা' WHERE `id` = 642;
UPDATE `upazilas` SET `name` = 'ফরিদপুর সদর' WHERE `id` = 643;
UPDATE `upazilas` SET `name` = 'বোয়ালমারী' WHERE `id` = 644;
UPDATE `upazilas` SET `name` = 'ভাঙ্গা' WHERE `id` = 645;
UPDATE `upazilas` SET `name` = 'মধুখালী' WHERE `id` = 646;
UPDATE `upazilas` SET `name` = 'সদরপুর' WHERE `id` = 647;
UPDATE `upazilas` SET `name` = 'সালথা' WHERE `id` = 648;
UPDATE `upazilas` SET `name` = 'ছাগলনাইয়া' WHERE `id` = 649;
UPDATE `upazilas` SET `name` = 'দাগনভূঞা' WHERE `id` = 650;
UPDATE `upazilas` SET `name` = 'পরশুরাম' WHERE `id` = 651;
UPDATE `upazilas` SET `name` = 'ফুলগাজী' WHERE `id` = 652;
UPDATE `upazilas` SET `name` = 'ফেনী সদর' WHERE `id` = 653;
UPDATE `upazilas` SET `name` = 'সোনাগাজী' WHERE `id` = 654;
UPDATE `upazilas` SET `name` = 'গাইবান্ধা সদর' WHERE `id` = 655;
UPDATE `upazilas` SET `name` = 'গোবিন্দগঞ্জ' WHERE `id` = 656;
UPDATE `upazilas` SET `name` = 'পলাশবাড়ী' WHERE `id` = 657;
UPDATE `upazilas` SET `name` = 'ফুলছড়ি' WHERE `id` = 658;
UPDATE `upazilas` SET `name` = 'সাঘাটা' WHERE `id` = 659;
UPDATE `upazilas` SET `name` = 'সাদুল্লাপুর' WHERE `id` = 660;
UPDATE `upazilas` SET `name` = 'সুন্দরগঞ্জ' WHERE `id` = 661;
UPDATE `upazilas` SET `name` = 'কাপাসিয়া' WHERE `id` = 662;
UPDATE `upazilas` SET `name` = 'কালিয়াকৈর' WHERE `id` = 663;
UPDATE `upazilas` SET `name` = 'কালীগঞ্জ' WHERE `id` = 664;
UPDATE `upazilas` SET `name` = 'গাজীপুর সদর' WHERE `id` = 665;
UPDATE `upazilas` SET `name` = 'গাজীপুর সিটি কর্পোরেশন' WHERE `id` = 666;
UPDATE `upazilas` SET `name` = 'শ্রীপুর' WHERE `id` = 667;
UPDATE `upazilas` SET `name` = 'কাশিয়ানী' WHERE `id` = 668;
UPDATE `upazilas` SET `name` = 'কোটালীপাড়া' WHERE `id` = 669;
UPDATE `upazilas` SET `name` = 'গোপালগঞ্জ সদর' WHERE `id` = 670;
UPDATE `upazilas` SET `name` = 'টুংগীপাড়া' WHERE `id` = 671;
UPDATE `upazilas` SET `name` = 'মুকসুদপুর' WHERE `id` = 672;
UPDATE `upazilas` SET `name` = 'আজমিরীগঞ্জ' WHERE `id` = 673;
UPDATE `upazilas` SET `name` = 'চুনারুঘাট' WHERE `id` = 674;
UPDATE `upazilas` SET `name` = 'নবীগঞ্জ' WHERE `id` = 675;
UPDATE `upazilas` SET `name` = 'বানিয়াচং' WHERE `id` = 676;
UPDATE `upazilas` SET `name` = 'বাহুবল' WHERE `id` = 677;
UPDATE `upazilas` SET `name` = 'মাধবপুর' WHERE `id` = 678;
UPDATE `upazilas` SET `name` = 'লাখাই' WHERE `id` = 679;
UPDATE `upazilas` SET `name` = 'শায়েস্তাগঞ্জ' WHERE `id` = 680;
UPDATE `upazilas` SET `name` = 'হবিগঞ্জ সদর' WHERE `id` = 681;
UPDATE `upazilas` SET `name` = 'আক্কেলপুর' WHERE `id` = 682;
UPDATE `upazilas` SET `name` = 'কালাই' WHERE `id` = 683;
UPDATE `upazilas` SET `name` = 'ক্ষেতলাল' WHERE `id` = 684;
UPDATE `upazilas` SET `name` = 'জয়পুরহাট সদর' WHERE `id` = 685;
UPDATE `upazilas` SET `name` = 'পাঁচবিবি' WHERE `id` = 686;
UPDATE `upazilas` SET `name` = 'ইসলামপুর' WHERE `id` = 687;
UPDATE `upazilas` SET `name` = 'জামালপুর সদর' WHERE `id` = 688;
UPDATE `upazilas` SET `name` = 'দেওয়ানগঞ্জ' WHERE `id` = 689;
UPDATE `upazilas` SET `name` = 'বকশীগঞ্জ' WHERE `id` = 690;
UPDATE `upazilas` SET `name` = 'মাদারগঞ্জ' WHERE `id` = 691;
UPDATE `upazilas` SET `name` = 'মেলান্দহ' WHERE `id` = 692;
UPDATE `upazilas` SET `name` = 'সরিষাবাড়ী' WHERE `id` = 693;
UPDATE `upazilas` SET `name` = 'অভয়নগর' WHERE `id` = 694;
UPDATE `upazilas` SET `name` = 'কেশবপুর' WHERE `id` = 695;
UPDATE `upazilas` SET `name` = 'চৌগাছা' WHERE `id` = 696;
UPDATE `upazilas` SET `name` = 'ঝিকরগাছা' WHERE `id` = 697;
UPDATE `upazilas` SET `name` = 'বাঘারপাড়া' WHERE `id` = 698;
UPDATE `upazilas` SET `name` = 'মণিরামপুর' WHERE `id` = 699;
UPDATE `upazilas` SET `name` = 'যশোর সদর' WHERE `id` = 700;
UPDATE `upazilas` SET `name` = 'শার্শা' WHERE `id` = 701;
UPDATE `upazilas` SET `name` = 'কাঠালিয়া' WHERE `id` = 702;
UPDATE `upazilas` SET `name` = 'ঝালকাঠি সদর' WHERE `id` = 703;
UPDATE `upazilas` SET `name` = 'নলছিটি' WHERE `id` = 704;
UPDATE `upazilas` SET `name` = 'রাজাপুর' WHERE `id` = 705;
UPDATE `upazilas` SET `name` = 'কালীগঞ্জ' WHERE `id` = 706;
UPDATE `upazilas` SET `name` = 'কোটচাঁদপুর' WHERE `id` = 707;
UPDATE `upazilas` SET `name` = 'ঝিনাইদহ সদর' WHERE `id` = 708;
UPDATE `upazilas` SET `name` = 'মহেশপুর' WHERE `id` = 709;
UPDATE `upazilas` SET `name` = 'শৈলকুপা' WHERE `id` = 710;
UPDATE `upazilas` SET `name` = 'হরিণাকুন্ডু' WHERE `id` = 711;
UPDATE `upazilas` SET `name` = 'খাগড়াছড়ি সদর' WHERE `id` = 712;
UPDATE `upazilas` SET `name` = 'গুইমারা' WHERE `id` = 713;
UPDATE `upazilas` SET `name` = 'দিঘীনালা' WHERE `id` = 714;
UPDATE `upazilas` SET `name` = 'পানছড়ি' WHERE `id` = 715;
UPDATE `upazilas` SET `name` = 'মহালছড়ি' WHERE `id` = 716;
UPDATE `upazilas` SET `name` = 'মাটিরাঙ্গা' WHERE `id` = 717;
UPDATE `upazilas` SET `name` = 'মানিকছড়ি' WHERE `id` = 718;
UPDATE `upazilas` SET `name` = 'রামগড়' WHERE `id` = 719;
UPDATE `upazilas` SET `name` = 'লক্ষীছড়ি' WHERE `id` = 720;
UPDATE `upazilas` SET `name` = 'কয়রা' WHERE `id` = 721;
UPDATE `upazilas` SET `name` = 'খুলনা সিটি কর্পোরেশন' WHERE `id` = 722;
UPDATE `upazilas` SET `name` = 'ডুমুরিয়া' WHERE `id` = 723;
UPDATE `upazilas` SET `name` = 'তেরখাদা' WHERE `id` = 724;
UPDATE `upazilas` SET `name` = 'দাকোপ' WHERE `id` = 725;
UPDATE `upazilas` SET `name` = 'দিঘলিয়া' WHERE `id` = 726;
UPDATE `upazilas` SET `name` = 'পাইকগাছা' WHERE `id` = 727;
UPDATE `upazilas` SET `name` = 'ফুলতলা' WHERE `id` = 728;
UPDATE `upazilas` SET `name` = 'বটিয়াঘাটা' WHERE `id` = 729;
UPDATE `upazilas` SET `name` = 'রূপসা' WHERE `id` = 730;
UPDATE `upazilas` SET `name` = 'অষ্টগ্রাম' WHERE `id` = 731;
UPDATE `upazilas` SET `name` = 'ইটনা' WHERE `id` = 732;
UPDATE `upazilas` SET `name` = 'কটিয়াদী' WHERE `id` = 733;
UPDATE `upazilas` SET `name` = 'করিমগঞ্জ' WHERE `id` = 734;
UPDATE `upazilas` SET `name` = 'কিশোরগঞ্জ সদর' WHERE `id` = 735;
UPDATE `upazilas` SET `name` = 'কুলিয়ারচর' WHERE `id` = 736;
UPDATE `upazilas` SET `name` = 'তাড়াইল' WHERE `id` = 737;
UPDATE `upazilas` SET `name` = 'নিকলী' WHERE `id` = 738;
UPDATE `upazilas` SET `name` = 'পাকুন্দিয়া' WHERE `id` = 739;
UPDATE `upazilas` SET `name` = 'বাজিতপুর' WHERE `id` = 740;
UPDATE `upazilas` SET `name` = 'ভৈরব' WHERE `id` = 741;
UPDATE `upazilas` SET `name` = 'মিঠামইন' WHERE `id` = 742;
UPDATE `upazilas` SET `name` = 'হোসেনপুর' WHERE `id` = 743;
UPDATE `upazilas` SET `name` = 'উলিপুর' WHERE `id` = 744;
UPDATE `upazilas` SET `name` = 'কুড়িগ্রাম সদর' WHERE `id` = 745;
UPDATE `upazilas` SET `name` = 'চর রাজিবপুর' WHERE `id` = 746;
UPDATE `upazilas` SET `name` = 'চিলমারী' WHERE `id` = 747;
UPDATE `upazilas` SET `name` = 'নাগেশ্বরী' WHERE `id` = 748;
UPDATE `upazilas` SET `name` = 'ফুলবাড়ী' WHERE `id` = 749;
UPDATE `upazilas` SET `name` = 'ভুরুঙ্গামারী' WHERE `id` = 750;
UPDATE `upazilas` SET `name` = 'রাজারহাট' WHERE `id` = 751;
UPDATE `upazilas` SET `name` = 'রৌমারী' WHERE `id` = 752;
UPDATE `upazilas` SET `name` = 'কুমারখালী' WHERE `id` = 753;
UPDATE `upazilas` SET `name` = 'কুষ্টিয়া সদর' WHERE `id` = 754;
UPDATE `upazilas` SET `name` = 'খোকসা' WHERE `id` = 755;
UPDATE `upazilas` SET `name` = 'দৌলতপুর' WHERE `id` = 756;
UPDATE `upazilas` SET `name` = 'ভেড়ামারা' WHERE `id` = 757;
UPDATE `upazilas` SET `name` = 'মিরপুর' WHERE `id` = 758;
UPDATE `upazilas` SET `name` = 'কমলনগর' WHERE `id` = 759;
UPDATE `upazilas` SET `name` = 'রামগঞ্জ' WHERE `id` = 760;
UPDATE `upazilas` SET `name` = 'রামগতি' WHERE `id` = 761;
UPDATE `upazilas` SET `name` = 'রায়পুর' WHERE `id` = 762;
UPDATE `upazilas` SET `name` = 'লক্ষ্মীপুর সদর' WHERE `id` = 763;
UPDATE `upazilas` SET `name` = 'আদিতমারী' WHERE `id` = 764;
UPDATE `upazilas` SET `name` = 'কালীগঞ্জ' WHERE `id` = 765;
UPDATE `upazilas` SET `name` = 'পাটগ্রাম' WHERE `id` = 766;
UPDATE `upazilas` SET `name` = 'লালমনিরহাট সদর' WHERE `id` = 767;
UPDATE `upazilas` SET `name` = 'হাতীবান্ধা' WHERE `id` = 768;
UPDATE `upazilas` SET `name` = 'কালকিনি' WHERE `id` = 769;
UPDATE `upazilas` SET `name` = 'মাদারীপুর সদর' WHERE `id` = 770;
UPDATE `upazilas` SET `name` = 'রাজৈর' WHERE `id` = 771;
UPDATE `upazilas` SET `name` = 'শিবচর' WHERE `id` = 772;
UPDATE `upazilas` SET `name` = 'মহম্মদপুর' WHERE `id` = 773;
UPDATE `upazilas` SET `name` = 'মাগুরা সদর' WHERE `id` = 774;
UPDATE `upazilas` SET `name` = 'শালিখা' WHERE `id` = 775;
UPDATE `upazilas` SET `name` = 'শ্রীপুর' WHERE `id` = 776;
UPDATE `upazilas` SET `name` = 'ঘিওর' WHERE `id` = 777;
UPDATE `upazilas` SET `name` = 'দৌলতপুর' WHERE `id` = 778;
UPDATE `upazilas` SET `name` = 'মানিকগঞ্জ সদর' WHERE `id` = 779;
UPDATE `upazilas` SET `name` = 'শিবালয়' WHERE `id` = 780;
UPDATE `upazilas` SET `name` = 'সাটুরিয়া' WHERE `id` = 781;
UPDATE `upazilas` SET `name` = 'সিংগাইর' WHERE `id` = 782;
UPDATE `upazilas` SET `name` = 'হরিরামপুর' WHERE `id` = 783;
UPDATE `upazilas` SET `name` = 'গাংনী' WHERE `id` = 784;
UPDATE `upazilas` SET `name` = 'মুজিবনগর' WHERE `id` = 785;
UPDATE `upazilas` SET `name` = 'মেহেরপুর সদর' WHERE `id` = 786;
UPDATE `upazilas` SET `name` = 'কমলগঞ্জ' WHERE `id` = 787;
UPDATE `upazilas` SET `name` = 'কুলাউড়া' WHERE `id` = 788;
UPDATE `upazilas` SET `name` = 'জুড়ী' WHERE `id` = 789;
UPDATE `upazilas` SET `name` = 'বড়লেখা' WHERE `id` = 790;
UPDATE `upazilas` SET `name` = 'মৌলভীবাজার সদর' WHERE `id` = 791;
UPDATE `upazilas` SET `name` = 'রাজনগর' WHERE `id` = 792;
UPDATE `upazilas` SET `name` = 'শ্রীমঙ্গল' WHERE `id` = 793;
UPDATE `upazilas` SET `name` = 'গজারিয়া' WHERE `id` = 794;
UPDATE `upazilas` SET `name` = 'টংগীবাড়ি' WHERE `id` = 795;
UPDATE `upazilas` SET `name` = 'মুন্সিগঞ্জ সদর' WHERE `id` = 796;
UPDATE `upazilas` SET `name` = 'লৌহজং' WHERE `id` = 797;
UPDATE `upazilas` SET `name` = 'শ্রীনগর' WHERE `id` = 798;
UPDATE `upazilas` SET `name` = 'সিরাজদিখান' WHERE `id` = 799;
UPDATE `upazilas` SET `name` = 'ঈশ্বরগঞ্জ' WHERE `id` = 800;
UPDATE `upazilas` SET `name` = 'গফরগাঁও' WHERE `id` = 801;
UPDATE `upazilas` SET `name` = 'গৌরীপুর' WHERE `id` = 802;
UPDATE `upazilas` SET `name` = 'তারাকান্দা' WHERE `id` = 803;
UPDATE `upazilas` SET `name` = 'ত্রিশাল' WHERE `id` = 804;
UPDATE `upazilas` SET `name` = 'ধোবাউড়া' WHERE `id` = 805;
UPDATE `upazilas` SET `name` = 'নান্দাইল' WHERE `id` = 806;
UPDATE `upazilas` SET `name` = 'ফুলপুর' WHERE `id` = 807;
UPDATE `upazilas` SET `name` = 'ফুলবাড়ীয়া' WHERE `id` = 808;
UPDATE `upazilas` SET `name` = 'ভালুকা' WHERE `id` = 809;
UPDATE `upazilas` SET `name` = 'ময়মনসিংহ সদর' WHERE `id` = 810;
UPDATE `upazilas` SET `name` = 'ময়মনসিংহ সিটি কর্পোরেশন' WHERE `id` = 811;
UPDATE `upazilas` SET `name` = 'মুক্তাগাছা' WHERE `id` = 812;
UPDATE `upazilas` SET `name` = 'হালুয়াঘাট' WHERE `id` = 813;
UPDATE `upazilas` SET `name` = 'আত্রাই' WHERE `id` = 814;
UPDATE `upazilas` SET `name` = 'ধামইরহাট' WHERE `id` = 815;
UPDATE `upazilas` SET `name` = 'নওগাঁ সদর' WHERE `id` = 816;
UPDATE `upazilas` SET `name` = 'নিয়ামতপুর' WHERE `id` = 817;
UPDATE `upazilas` SET `name` = 'পত্নিতলা' WHERE `id` = 818;
UPDATE `upazilas` SET `name` = 'পোরশা' WHERE `id` = 819;
UPDATE `upazilas` SET `name` = 'বদলগাছী' WHERE `id` = 820;
UPDATE `upazilas` SET `name` = 'মহাদেবপুর' WHERE `id` = 821;
UPDATE `upazilas` SET `name` = 'মান্দা' WHERE `id` = 822;
UPDATE `upazilas` SET `name` = 'রাণীনগর' WHERE `id` = 823;
UPDATE `upazilas` SET `name` = 'সাপাহার' WHERE `id` = 824;
UPDATE `upazilas` SET `name` = 'কালিয়া' WHERE `id` = 825;
UPDATE `upazilas` SET `name` = 'নড়াইল সদর' WHERE `id` = 826;
UPDATE `upazilas` SET `name` = 'লোহাগড়া' WHERE `id` = 827;
UPDATE `upazilas` SET `name` = 'আড়াইহাজার' WHERE `id` = 828;
UPDATE `upazilas` SET `name` = 'নারায়ণগঞ্জ সিটি কর্পোরেশন' WHERE `id` = 829;
UPDATE `upazilas` SET `name` = 'নারায়নগঞ্জ সদর' WHERE `id` = 830;
UPDATE `upazilas` SET `name` = 'বন্দর' WHERE `id` = 831;
UPDATE `upazilas` SET `name` = 'রূপগঞ্জ' WHERE `id` = 832;
UPDATE `upazilas` SET `name` = 'সোনারগাঁ' WHERE `id` = 833;
UPDATE `upazilas` SET `name` = 'নরসিংদী সদর' WHERE `id` = 834;
UPDATE `upazilas` SET `name` = 'পলাশ' WHERE `id` = 835;
UPDATE `upazilas` SET `name` = 'বেলাবো' WHERE `id` = 836;
UPDATE `upazilas` SET `name` = 'মনোহরদী' WHERE `id` = 837;
UPDATE `upazilas` SET `name` = 'রায়পুরা' WHERE `id` = 838;
UPDATE `upazilas` SET `name` = 'শিবপুর' WHERE `id` = 839;
UPDATE `upazilas` SET `name` = 'গুরুদাসপুর' WHERE `id` = 840;
UPDATE `upazilas` SET `name` = 'নলডাঙ্গা' WHERE `id` = 841;
UPDATE `upazilas` SET `name` = 'নাটোর সদর' WHERE `id` = 842;
UPDATE `upazilas` SET `name` = 'বড়াইগ্রাম' WHERE `id` = 843;
UPDATE `upazilas` SET `name` = 'বাগাতিপাড়া' WHERE `id` = 844;
UPDATE `upazilas` SET `name` = 'লালপুর' WHERE `id` = 845;
UPDATE `upazilas` SET `name` = 'সিংড়া' WHERE `id` = 846;
UPDATE `upazilas` SET `name` = 'গোমস্তাপুর' WHERE `id` = 847;
UPDATE `upazilas` SET `name` = 'চাঁপাইনবাবগঞ্জ সদর' WHERE `id` = 848;
UPDATE `upazilas` SET `name` = 'নাচোল' WHERE `id` = 849;
UPDATE `upazilas` SET `name` = 'ভোলাহাট' WHERE `id` = 850;
UPDATE `upazilas` SET `name` = 'শিবগঞ্জ' WHERE `id` = 851;
UPDATE `upazilas` SET `name` = 'আটপাড়া' WHERE `id` = 852;
UPDATE `upazilas` SET `name` = 'কলমাকান্দা' WHERE `id` = 853;
UPDATE `upazilas` SET `name` = 'কেন্দুয়া' WHERE `id` = 854;
UPDATE `upazilas` SET `name` = 'খালিয়াজুরী' WHERE `id` = 855;
UPDATE `upazilas` SET `name` = 'দুর্গাপুর' WHERE `id` = 856;
UPDATE `upazilas` SET `name` = 'নেত্রকোণা সদর' WHERE `id` = 857;
UPDATE `upazilas` SET `name` = 'পূর্বধলা' WHERE `id` = 858;
UPDATE `upazilas` SET `name` = 'বারহাট্টা' WHERE `id` = 859;
UPDATE `upazilas` SET `name` = 'মদন' WHERE `id` = 860;
UPDATE `upazilas` SET `name` = 'মোহনগঞ্জ' WHERE `id` = 861;
UPDATE `upazilas` SET `name` = 'কিশোরগঞ্জ' WHERE `id` = 862;
UPDATE `upazilas` SET `name` = 'জলঢাকা' WHERE `id` = 863;
UPDATE `upazilas` SET `name` = 'ডিমলা' WHERE `id` = 864;
UPDATE `upazilas` SET `name` = 'ডোমার' WHERE `id` = 865;
UPDATE `upazilas` SET `name` = 'নীলফামারী সদর' WHERE `id` = 866;
UPDATE `upazilas` SET `name` = 'সৈয়দপুর' WHERE `id` = 867;
UPDATE `upazilas` SET `name` = 'কবিরহাট' WHERE `id` = 868;
UPDATE `upazilas` SET `name` = 'কোম্পানীগঞ্জ' WHERE `id` = 869;
UPDATE `upazilas` SET `name` = 'চাটখিল' WHERE `id` = 870;
UPDATE `upazilas` SET `name` = 'নোয়াখালী সদর' WHERE `id` = 871;
UPDATE `upazilas` SET `name` = 'বেগমগঞ্জ' WHERE `id` = 872;
UPDATE `upazilas` SET `name` = 'সুবর্ণচর' WHERE `id` = 873;
UPDATE `upazilas` SET `name` = 'সেনবাগ' WHERE `id` = 874;
UPDATE `upazilas` SET `name` = 'সোনাইমুড়ী' WHERE `id` = 875;
UPDATE `upazilas` SET `name` = 'হাতিয়া' WHERE `id` = 876;
UPDATE `upazilas` SET `name` = 'আটঘরিয়া' WHERE `id` = 877;
UPDATE `upazilas` SET `name` = 'ঈশ্বরদী' WHERE `id` = 878;
UPDATE `upazilas` SET `name` = 'চাটমোহর' WHERE `id` = 879;
UPDATE `upazilas` SET `name` = 'পাবনা সদর' WHERE `id` = 880;
UPDATE `upazilas` SET `name` = 'ফরিদপুর' WHERE `id` = 881;
UPDATE `upazilas` SET `name` = 'বেড়া' WHERE `id` = 882;
UPDATE `upazilas` SET `name` = 'ভাঙ্গুড়া' WHERE `id` = 883;
UPDATE `upazilas` SET `name` = 'সাঁথিয়া' WHERE `id` = 884;
UPDATE `upazilas` SET `name` = 'সুজানগর' WHERE `id` = 885;
UPDATE `upazilas` SET `name` = 'আটোয়ারী' WHERE `id` = 886;
UPDATE `upazilas` SET `name` = 'তেতুলিয়া' WHERE `id` = 887;
UPDATE `upazilas` SET `name` = 'দেবীগঞ্জ' WHERE `id` = 888;
UPDATE `upazilas` SET `name` = 'পঞ্চগড় সদর' WHERE `id` = 889;
UPDATE `upazilas` SET `name` = 'বোদা' WHERE `id` = 890;
UPDATE `upazilas` SET `name` = 'কলাপাড়া' WHERE `id` = 891;
UPDATE `upazilas` SET `name` = 'গলাচিপা' WHERE `id` = 892;
UPDATE `upazilas` SET `name` = 'দশমিনা' WHERE `id` = 893;
UPDATE `upazilas` SET `name` = 'দুমকি' WHERE `id` = 894;
UPDATE `upazilas` SET `name` = 'পটুয়াখালী সদর' WHERE `id` = 895;
UPDATE `upazilas` SET `name` = 'বাউফল' WHERE `id` = 896;
UPDATE `upazilas` SET `name` = 'মির্জাগঞ্জ' WHERE `id` = 897;
UPDATE `upazilas` SET `name` = 'রাঙ্গাবালী' WHERE `id` = 898;
UPDATE `upazilas` SET `name` = 'কাউখালী' WHERE `id` = 899;
UPDATE `upazilas` SET `name` = 'জিয়ানগর' WHERE `id` = 900;
UPDATE `upazilas` SET `name` = 'নাজিরপুর' WHERE `id` = 901;
UPDATE `upazilas` SET `name` = 'নেছারাবাদ' WHERE `id` = 902;
UPDATE `upazilas` SET `name` = 'পিরোজপুর সদর' WHERE `id` = 903;
UPDATE `upazilas` SET `name` = 'ভান্ডারিয়া' WHERE `id` = 904;
UPDATE `upazilas` SET `name` = 'মঠবাড়ীয়া' WHERE `id` = 905;
UPDATE `upazilas` SET `name` = 'গোদাগাড়ী' WHERE `id` = 906;
UPDATE `upazilas` SET `name` = 'চারঘাট' WHERE `id` = 907;
UPDATE `upazilas` SET `name` = 'তানোর' WHERE `id` = 908;
UPDATE `upazilas` SET `name` = 'দুর্গাপুর' WHERE `id` = 909;
UPDATE `upazilas` SET `name` = 'পবা' WHERE `id` = 910;
UPDATE `upazilas` SET `name` = 'পুঠিয়া' WHERE `id` = 911;
UPDATE `upazilas` SET `name` = 'বাগমারা' WHERE `id` = 912;
UPDATE `upazilas` SET `name` = 'বাঘা' WHERE `id` = 913;
UPDATE `upazilas` SET `name` = 'মোহনপুর' WHERE `id` = 914;
UPDATE `upazilas` SET `name` = 'রাজশাহী সিটি কর্পোরেশন' WHERE `id` = 915;
UPDATE `upazilas` SET `name` = 'কালুখালী' WHERE `id` = 916;
UPDATE `upazilas` SET `name` = 'গোয়ালন্দ' WHERE `id` = 917;
UPDATE `upazilas` SET `name` = 'পাংশা' WHERE `id` = 918;
UPDATE `upazilas` SET `name` = 'বালিয়াকান্দি' WHERE `id` = 919;
UPDATE `upazilas` SET `name` = 'রাজবাড়ী সদর' WHERE `id` = 920;
UPDATE `upazilas` SET `name` = 'কাউখালী' WHERE `id` = 921;
UPDATE `upazilas` SET `name` = 'কাপ্তাই' WHERE `id` = 922;
UPDATE `upazilas` SET `name` = 'জুরাছড়ি' WHERE `id` = 923;
UPDATE `upazilas` SET `name` = 'নানিয়ারচর' WHERE `id` = 924;
UPDATE `upazilas` SET `name` = 'বরকল' WHERE `id` = 925;
UPDATE `upazilas` SET `name` = 'বাঘাইছড়ি' WHERE `id` = 926;
UPDATE `upazilas` SET `name` = 'বিলাইছড়ি' WHERE `id` = 927;
UPDATE `upazilas` SET `name` = 'রাঙ্গামাটি সদর' WHERE `id` = 928;
UPDATE `upazilas` SET `name` = 'রাজস্থলী' WHERE `id` = 929;
UPDATE `upazilas` SET `name` = 'লংগদু' WHERE `id` = 930;
UPDATE `upazilas` SET `name` = 'কাউনিয়া' WHERE `id` = 931;
UPDATE `upazilas` SET `name` = 'গংগাচড়া' WHERE `id` = 932;
UPDATE `upazilas` SET `name` = 'তারাগঞ্জ' WHERE `id` = 933;
UPDATE `upazilas` SET `name` = 'পীরগঞ্জ' WHERE `id` = 934;
UPDATE `upazilas` SET `name` = 'পীরগাছা' WHERE `id` = 935;
UPDATE `upazilas` SET `name` = 'বদরগঞ্জ' WHERE `id` = 936;
UPDATE `upazilas` SET `name` = 'মিঠাপুকুর' WHERE `id` = 937;
UPDATE `upazilas` SET `name` = 'রংপুর সদর' WHERE `id` = 938;
UPDATE `upazilas` SET `name` = 'রংপুর সিটি কর্পোরেশন' WHERE `id` = 939;
UPDATE `upazilas` SET `name` = 'গোসাইরহাট' WHERE `id` = 940;
UPDATE `upazilas` SET `name` = 'জাজিরা' WHERE `id` = 941;
UPDATE `upazilas` SET `name` = 'ডামুড্যা' WHERE `id` = 942;
UPDATE `upazilas` SET `name` = 'নড়িয়া' WHERE `id` = 943;
UPDATE `upazilas` SET `name` = 'ভেদরগঞ্জ' WHERE `id` = 944;
UPDATE `upazilas` SET `name` = 'শরিয়তপুর সদর' WHERE `id` = 945;
UPDATE `upazilas` SET `name` = 'আশাশুনি' WHERE `id` = 946;
UPDATE `upazilas` SET `name` = 'কলারোয়া' WHERE `id` = 947;
UPDATE `upazilas` SET `name` = 'কালিগঞ্জ' WHERE `id` = 948;
UPDATE `upazilas` SET `name` = 'তালা' WHERE `id` = 949;
UPDATE `upazilas` SET `name` = 'দেবহাটা' WHERE `id` = 950;
UPDATE `upazilas` SET `name` = 'শ্যামনগর' WHERE `id` = 951;
UPDATE `upazilas` SET `name` = 'সাতক্ষীরা সদর' WHERE `id` = 952;
UPDATE `upazilas` SET `name` = 'উল্লাপাড়া' WHERE `id` = 953;
UPDATE `upazilas` SET `name` = 'কাজীপুর' WHERE `id` = 954;
UPDATE `upazilas` SET `name` = 'কামারখন্দ' WHERE `id` = 955;
UPDATE `upazilas` SET `name` = 'চৌহালি' WHERE `id` = 956;
UPDATE `upazilas` SET `name` = 'তাড়াশ' WHERE `id` = 957;
UPDATE `upazilas` SET `name` = 'বেলকুচি' WHERE `id` = 958;
UPDATE `upazilas` SET `name` = 'রায়গঞ্জ' WHERE `id` = 959;
UPDATE `upazilas` SET `name` = 'শাহজাদপুর' WHERE `id` = 960;
UPDATE `upazilas` SET `name` = 'সিরাজগঞ্জ সদর' WHERE `id` = 961;
UPDATE `upazilas` SET `name` = 'ঝিনাইগাতী' WHERE `id` = 962;
UPDATE `upazilas` SET `name` = 'নকলা' WHERE `id` = 963;
UPDATE `upazilas` SET `name` = 'নালিতাবাড়ী' WHERE `id` = 964;
UPDATE `upazilas` SET `name` = 'শেরপুর সদর' WHERE `id` = 965;
UPDATE `upazilas` SET `name` = 'শ্রীবরদী' WHERE `id` = 966;
UPDATE `upazilas` SET `name` = 'ছাতক' WHERE `id` = 967;
UPDATE `upazilas` SET `name` = 'জগন্নাথপুর' WHERE `id` = 968;
UPDATE `upazilas` SET `name` = 'জামালগঞ্জ' WHERE `id` = 969;
UPDATE `upazilas` SET `name` = 'তাহিরপুর' WHERE `id` = 970;
UPDATE `upazilas` SET `name` = 'দক্ষিণ সুনামগঞ্জ' WHERE `id` = 971;
UPDATE `upazilas` SET `name` = 'দিরাই' WHERE `id` = 972;
UPDATE `upazilas` SET `name` = 'দোয়ারাবাজার' WHERE `id` = 973;
UPDATE `upazilas` SET `name` = 'ধর্মপাশা' WHERE `id` = 974;
UPDATE `upazilas` SET `name` = 'বিশ্বম্ভরপুর' WHERE `id` = 975;
UPDATE `upazilas` SET `name` = 'শাল্লা' WHERE `id` = 976;
UPDATE `upazilas` SET `name` = 'সুনামগঞ্জ সদর' WHERE `id` = 977;
UPDATE `upazilas` SET `name` = 'ওসমানী নগর' WHERE `id` = 978;
UPDATE `upazilas` SET `name` = 'কানাইঘাট' WHERE `id` = 979;
UPDATE `upazilas` SET `name` = 'কোম্পানীগঞ্জ' WHERE `id` = 980;
UPDATE `upazilas` SET `name` = 'গোয়াইনঘাট' WHERE `id` = 981;
UPDATE `upazilas` SET `name` = 'গোলাপগঞ্জ' WHERE `id` = 982;
UPDATE `upazilas` SET `name` = 'জকিগঞ্জ' WHERE `id` = 983;
UPDATE `upazilas` SET `name` = 'জৈন্তাপুর' WHERE `id` = 984;
UPDATE `upazilas` SET `name` = 'দক্ষিণ সুরমা' WHERE `id` = 985;
UPDATE `upazilas` SET `name` = 'ফেঞ্চুগঞ্জ' WHERE `id` = 986;
UPDATE `upazilas` SET `name` = 'বালাগঞ্জ' WHERE `id` = 987;
UPDATE `upazilas` SET `name` = 'বিয়ানীবাজার' WHERE `id` = 988;
UPDATE `upazilas` SET `name` = 'বিশ্বনাথ' WHERE `id` = 989;
UPDATE `upazilas` SET `name` = 'সিলেট সদর' WHERE `id` = 990;
UPDATE `upazilas` SET `name` = 'সিলেট সিটি কর্পোরেশন' WHERE `id` = 991;
UPDATE `upazilas` SET `name` = 'কালিহাতী' WHERE `id` = 992;
UPDATE `upazilas` SET `name` = 'গোপালপুর' WHERE `id` = 993;
UPDATE `upazilas` SET `name` = 'ঘাটাইল' WHERE `id` = 994;
UPDATE `upazilas` SET `name` = 'টাঙ্গাইল সদর' WHERE `id` = 995;
UPDATE `upazilas` SET `name` = 'দেলদুয়ার' WHERE `id` = 996;
UPDATE `upazilas` SET `name` = 'ধনবাড়ী' WHERE `id` = 997;
UPDATE `upazilas` SET `name` = 'নাগরপুর' WHERE `id` = 998;
UPDATE `upazilas` SET `name` = 'বাসাইল' WHERE `id` = 999;
UPDATE `upazilas` SET `name` = 'ভুয়াপুর' WHERE `id` = 1000;
UPDATE `upazilas` SET `name` = 'মধুপুর' WHERE `id` = 1001;
UPDATE `upazilas` SET `name` = 'মির্জাপুর' WHERE `id` = 1002;
UPDATE `upazilas` SET `name` = 'সখিপুর' WHERE `id` = 1003;
UPDATE `upazilas` SET `name` = 'ঠাকুরগাঁও সদর' WHERE `id` = 1004;
UPDATE `upazilas` SET `name` = 'পীরগঞ্জ' WHERE `id` = 1005;
UPDATE `upazilas` SET `name` = 'বালিয়াডাঙ্গী' WHERE `id` = 1006;
UPDATE `upazilas` SET `name` = 'রাণীশংকৈল' WHERE `id` = 1007;
UPDATE `upazilas` SET `name` = 'হরিপুর' WHERE `id` = 1008;